### ISSUE TITLE
Allow script files also

### ISSUE THREAD

**Issue by shahankit** [juntalis/htmlminify.py#1]
Instead of skipping script files i want to include then as it's included by original kangax here: https://kangax.github.io/html-minifier. I tried example that's provided by you in readme.

**Comment by juntalis** [comment]
Yeah, this was written back in 2011 when kangax's project was still at v0.3. I went ahead and updated it for your request.

Probably won't be any more updates after this one.

**Comment by shahankit** [comment]
@juntalis thank you for updating.
